[2023-12-21T15:32:05.171+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509
[2023-12-21T15:32:05.184+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test***'
[2023-12-21T15:32:05.365+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509
[2023-12-21T15:32:05.367+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test***'
[2023-12-21T15:32:05.683+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:13:27.619896+00:00 [queued]>
[2023-12-21T15:32:05.721+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:13:27.619896+00:00 [queued]>
[2023-12-21T15:32:05.724+0000] {taskinstance.py:1361} INFO - Starting attempt 8 of 8
[2023-12-21T15:32:05.815+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): testairflow> on 2023-12-21 15:13:27.619896+00:00
[2023-12-21T15:32:05.851+0000] {standard_task_runner.py:57} INFO - Started process 108 to run task
[2023-12-21T15:32:05.896+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraping-jobs', 'test***', 'manual__2023-12-21T15:13:27.619896+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/apps/webscrapinglinkedin/dag-webscrapinglinkedin.py', '--cfg-path', '/tmp/tmpz3hkcjzt']
[2023-12-21T15:32:05.898+0000] {standard_task_runner.py:85} INFO - Job 37: Subtask test***
[2023-12-21T15:32:06.226+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509
[2023-12-21T15:32:06.227+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test***'
[2023-12-21T15:32:06.236+0000] {task_command.py:416} INFO - Running <TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:13:27.619896+00:00 [running]> on host f3c3b333e615
[2023-12-21T15:32:06.884+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping-jobs' AIRFLOW_CTX_TASK_ID='test***' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T15:13:27.619896+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T15:13:27.619896+00:00'
[2023-12-21T15:32:06.914+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T15:32:06.916+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/apps/webscrapinglinkedin/aux-pedreiro.py']
[2023-12-21T15:32:07.001+0000] {subprocess.py:86} INFO - Output:
[2023-12-21T15:32:07.591+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T15:32:07.592+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/apps/webscrapinglinkedin/aux-pedreiro.py", line 1, in <module>
[2023-12-21T15:32:07.594+0000] {subprocess.py:93} INFO -     from lib.browser import browser
[2023-12-21T15:32:07.595+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'lib'
[2023-12-21T15:32:07.605+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-21T15:32:07.643+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-21T15:32:07.662+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scraping-jobs, task_id=test***, execution_date=20231221T151327, start_date=20231221T153205, end_date=20231221T153207
[2023-12-21T15:32:07.725+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 37 for task test*** (Bash command failed. The command returned a non-zero exit code 1.; 108)
[2023-12-21T15:32:07.789+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T15:32:07.846+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
