[2023-12-21T15:24:07.293+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509
[2023-12-21T15:24:07.296+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test***'
[2023-12-21T15:24:07.372+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509
[2023-12-21T15:24:07.374+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test***'
[2023-12-21T15:24:07.469+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:13:27.619896+00:00 [queued]>
[2023-12-21T15:24:07.492+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:13:27.619896+00:00 [queued]>
[2023-12-21T15:24:07.493+0000] {taskinstance.py:1361} INFO - Starting attempt 7 of 7
[2023-12-21T15:24:07.538+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): testairflow> on 2023-12-21 15:13:27.619896+00:00
[2023-12-21T15:24:07.550+0000] {standard_task_runner.py:57} INFO - Started process 1243 to run task
[2023-12-21T15:24:07.578+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraping-jobs', 'test***', 'manual__2023-12-21T15:13:27.619896+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/apps/webscrapinglinkedin/dag-webscrapinglinkedin.py', '--cfg-path', '/tmp/tmpzmzeumm3']
[2023-12-21T15:24:07.581+0000] {standard_task_runner.py:85} INFO - Job 34: Subtask test***
[2023-12-21T15:24:07.705+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509
[2023-12-21T15:24:07.711+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test***'
[2023-12-21T15:24:07.722+0000] {task_command.py:416} INFO - Running <TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:13:27.619896+00:00 [running]> on host ae1e32dc581d
[2023-12-21T15:24:07.955+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping-jobs' AIRFLOW_CTX_TASK_ID='test***' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T15:13:27.619896+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T15:13:27.619896+00:00'
[2023-12-21T15:24:07.962+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T15:24:07.965+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/apps/webscrapinglinkedin/aux-pedreiro.py']
[2023-12-21T15:24:07.988+0000] {subprocess.py:86} INFO - Output:
[2023-12-21T15:24:08.423+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T15:24:08.425+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/apps/webscrapinglinkedin/aux-pedreiro.py", line 1, in <module>
[2023-12-21T15:24:08.427+0000] {subprocess.py:93} INFO -     from lib.browser import browser
[2023-12-21T15:24:08.432+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'lib'
[2023-12-21T15:24:08.433+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-21T15:24:08.489+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-21T15:24:08.499+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scraping-jobs, task_id=test***, execution_date=20231221T151327, start_date=20231221T152407, end_date=20231221T152408
[2023-12-21T15:24:08.846+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 34 for task test*** (Bash command failed. The command returned a non-zero exit code 1.; 1243)
[2023-12-21T15:24:08.905+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T15:24:09.127+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
