[2023-12-21T15:44:11.592+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509
[2023-12-21T15:44:11.594+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test***'
[2023-12-21T15:44:11.644+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509
[2023-12-21T15:44:11.648+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test***'
[2023-12-21T15:44:11.709+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:13:27.619896+00:00 [queued]>
[2023-12-21T15:44:11.725+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:13:27.619896+00:00 [queued]>
[2023-12-21T15:44:11.727+0000] {taskinstance.py:1361} INFO - Starting attempt 11 of 11
[2023-12-21T15:44:11.752+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): testairflow> on 2023-12-21 15:13:27.619896+00:00
[2023-12-21T15:44:11.763+0000] {standard_task_runner.py:57} INFO - Started process 130 to run task
[2023-12-21T15:44:11.768+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraping-jobs', 'test***', 'manual__2023-12-21T15:13:27.619896+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/webscrapinglinkedin/dag-webscrapinglinkedin.py', '--cfg-path', '/tmp/tmpbix399ze']
[2023-12-21T15:44:11.770+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask test***
[2023-12-21T15:44:11.898+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509
[2023-12-21T15:44:11.899+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test***'
[2023-12-21T15:44:11.904+0000] {task_command.py:416} INFO - Running <TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:13:27.619896+00:00 [running]> on host cdaea2bd355d
[2023-12-21T15:44:12.039+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping-jobs' AIRFLOW_CTX_TASK_ID='test***' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T15:13:27.619896+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T15:13:27.619896+00:00'
[2023-12-21T15:44:12.042+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T15:44:12.046+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/apps/webscrapinglinkedin/aux-pedreiro.py']
[2023-12-21T15:44:12.081+0000] {subprocess.py:86} INFO - Output:
[2023-12-21T15:44:12.336+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/dags/apps/webscrapinglinkedin/aux-pedreiro.py': [Errno 2] No such file or directory
[2023-12-21T15:44:12.341+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-12-21T15:44:12.358+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-12-21T15:44:12.364+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scraping-jobs, task_id=test***, execution_date=20231221T151327, start_date=20231221T154411, end_date=20231221T154412
[2023-12-21T15:44:12.387+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 42 for task test*** (Bash command failed. The command returned a non-zero exit code 2.; 130)
[2023-12-21T15:44:12.428+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T15:44:12.457+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
