[2023-12-21T15:44:53.930+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509
[2023-12-21T15:44:53.932+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test***'
[2023-12-21T15:44:53.996+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509
[2023-12-21T15:44:53.998+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test***'
[2023-12-21T15:44:54.075+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:13:27.619896+00:00 [queued]>
[2023-12-21T15:44:54.095+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:13:27.619896+00:00 [queued]>
[2023-12-21T15:44:54.097+0000] {taskinstance.py:1361} INFO - Starting attempt 12 of 12
[2023-12-21T15:44:54.123+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): testairflow> on 2023-12-21 15:13:27.619896+00:00
[2023-12-21T15:44:54.140+0000] {standard_task_runner.py:57} INFO - Started process 141 to run task
[2023-12-21T15:44:54.147+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraping-jobs', 'test***', 'manual__2023-12-21T15:13:27.619896+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/webscrapinglinkedin/dag-webscrapinglinkedin.py', '--cfg-path', '/tmp/tmpmndqyuh0']
[2023-12-21T15:44:54.159+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask test***
[2023-12-21T15:44:54.329+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509
[2023-12-21T15:44:54.331+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test***'
[2023-12-21T15:44:54.349+0000] {task_command.py:416} INFO - Running <TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:13:27.619896+00:00 [running]> on host cdaea2bd355d
[2023-12-21T15:44:54.580+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping-jobs' AIRFLOW_CTX_TASK_ID='test***' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T15:13:27.619896+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T15:13:27.619896+00:00'
[2023-12-21T15:44:54.584+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T15:44:54.587+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/webscrapinglinkedin/aux-pedreiro.py']
[2023-12-21T15:44:54.609+0000] {subprocess.py:86} INFO - Output:
[2023-12-21T15:44:54.955+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T15:44:54.957+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/webscrapinglinkedin/aux-pedreiro.py", line 1, in <module>
[2023-12-21T15:44:54.958+0000] {subprocess.py:93} INFO -     from lib.browser import browser
[2023-12-21T15:44:54.959+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'lib'
[2023-12-21T15:44:54.963+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-21T15:44:54.984+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-21T15:44:54.993+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scraping-jobs, task_id=test***, execution_date=20231221T151327, start_date=20231221T154454, end_date=20231221T154454
[2023-12-21T15:44:55.015+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 43 for task test*** (Bash command failed. The command returned a non-zero exit code 1.; 141)
[2023-12-21T15:44:55.067+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T15:44:55.103+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
