[2023-12-21T14:38:03.337+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T13:23:03.607351+00:00/task_id=test*** permission to 509
[2023-12-21T14:38:03.339+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T13:23:03.607351+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T13:23:03.607351+00:00/task_id=test***'
[2023-12-21T14:38:03.383+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T13:23:03.607351+00:00/task_id=test*** permission to 509
[2023-12-21T14:38:03.385+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T13:23:03.607351+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T13:23:03.607351+00:00/task_id=test***'
[2023-12-21T14:38:03.476+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T13:23:03.607351+00:00 [queued]>
[2023-12-21T14:38:03.498+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T13:23:03.607351+00:00 [queued]>
[2023-12-21T14:38:03.500+0000] {taskinstance.py:1361} INFO - Starting attempt 9 of 9
[2023-12-21T14:38:03.526+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): testairflow> on 2023-12-21 13:23:03.607351+00:00
[2023-12-21T14:38:03.536+0000] {standard_task_runner.py:57} INFO - Started process 551 to run task
[2023-12-21T14:38:03.541+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraping-jobs', 'test***', 'manual__2023-12-21T13:23:03.607351+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dag-webscrappinglinkedin.py', '--cfg-path', '/tmp/tmpmbt7sk06']
[2023-12-21T14:38:03.543+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask test***
[2023-12-21T14:38:03.625+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T13:23:03.607351+00:00/task_id=test*** permission to 509
[2023-12-21T14:38:03.626+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T13:23:03.607351+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T13:23:03.607351+00:00/task_id=test***'
[2023-12-21T14:38:03.632+0000] {task_command.py:416} INFO - Running <TaskInstance: scraping-jobs.testairflow manual__2023-12-21T13:23:03.607351+00:00 [running]> on host ae1e32dc581d
[2023-12-21T14:38:03.753+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping-jobs' AIRFLOW_CTX_TASK_ID='test***' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T13:23:03.607351+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T13:23:03.607351+00:00'
[2023-12-21T14:38:03.756+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T14:38:03.758+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/apps/crawler.py']
[2023-12-21T14:38:03.789+0000] {subprocess.py:86} INFO - Output:
[2023-12-21T14:38:12.250+0000] {subprocess.py:93} INFO - Scrolling page...
[2023-12-21T14:38:12.318+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T14:38:12.319+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/apps/crawler.py", line 66, in <module>
[2023-12-21T14:38:12.320+0000] {subprocess.py:93} INFO -     job_description = WebDriverWait(driver, 2).until(EC.presence_of_element_located((By.XPATH, f'//*[@id="main-content"]/section[2]/ul/li[{n}]/div'))).text
[2023-12-21T14:38:12.327+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 92, in until
[2023-12-21T14:38:12.329+0000] {subprocess.py:93} INFO -     value = method(self._driver)
[2023-12-21T14:38:12.333+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py", line 80, in _predicate
[2023-12-21T14:38:12.334+0000] {subprocess.py:93} INFO -     return driver.find_element(*locator)
[2023-12-21T14:38:12.335+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 741, in find_element
[2023-12-21T14:38:12.336+0000] {subprocess.py:93} INFO -     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
[2023-12-21T14:38:12.343+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
[2023-12-21T14:38:12.346+0000] {subprocess.py:93} INFO -     self.error_handler.check_response(response)
[2023-12-21T14:38:12.349+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2023-12-21T14:38:12.351+0000] {subprocess.py:93} INFO -     raise exception_class(message, screen, stacktrace)
[2023-12-21T14:38:12.352+0000] {subprocess.py:93} INFO - selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
[2023-12-21T14:38:12.354+0000] {subprocess.py:93} INFO - from unknown error: cannot determine loading status
[2023-12-21T14:38:12.358+0000] {subprocess.py:93} INFO - from tab crashed
[2023-12-21T14:38:12.360+0000] {subprocess.py:93} INFO -   (Session info: headless chrome=117.0.5938.62)
[2023-12-21T14:38:12.361+0000] {subprocess.py:93} INFO - Stacktrace:
[2023-12-21T14:38:12.362+0000] {subprocess.py:93} INFO - #0 0x55cd86208c07 <unknown>
[2023-12-21T14:38:12.365+0000] {subprocess.py:93} INFO - #1 0x55cd85eecd4a <unknown>
[2023-12-21T14:38:12.366+0000] {subprocess.py:93} INFO - #2 0x55cd85ed8733 <unknown>
[2023-12-21T14:38:12.368+0000] {subprocess.py:93} INFO - #3 0x55cd85ed7678 <unknown>
[2023-12-21T14:38:12.369+0000] {subprocess.py:93} INFO - #4 0x55cd85ed7c7d <unknown>
[2023-12-21T14:38:12.370+0000] {subprocess.py:93} INFO - #5 0x55cd85ee4dd8 <unknown>
[2023-12-21T14:38:12.377+0000] {subprocess.py:93} INFO - #6 0x55cd85ef7703 <unknown>
[2023-12-21T14:38:12.378+0000] {subprocess.py:93} INFO - #7 0x55cd85efb8bf <unknown>
[2023-12-21T14:38:12.380+0000] {subprocess.py:93} INFO - #8 0x55cd85ed814e <unknown>
[2023-12-21T14:38:12.382+0000] {subprocess.py:93} INFO - #9 0x55cd85ef73e6 <unknown>
[2023-12-21T14:38:12.383+0000] {subprocess.py:93} INFO - #10 0x55cd85f66413 <unknown>
[2023-12-21T14:38:12.384+0000] {subprocess.py:93} INFO - #11 0x55cd85f4f9b7 <unknown>
[2023-12-21T14:38:12.385+0000] {subprocess.py:93} INFO - #12 0x55cd85f24cad <unknown>
[2023-12-21T14:38:12.386+0000] {subprocess.py:93} INFO - #13 0x55cd85f26266 <unknown>
[2023-12-21T14:38:12.393+0000] {subprocess.py:93} INFO - #14 0x55cd861dcc00 <unknown>
[2023-12-21T14:38:12.397+0000] {subprocess.py:93} INFO - #15 0x55cd861dfdad <unknown>
[2023-12-21T14:38:12.398+0000] {subprocess.py:93} INFO - #16 0x55cd861df84a <unknown>
[2023-12-21T14:38:12.400+0000] {subprocess.py:93} INFO - #17 0x55cd861e02c9 <unknown>
[2023-12-21T14:38:12.401+0000] {subprocess.py:93} INFO - #18 0x55cd861e67e3 <unknown>
[2023-12-21T14:38:12.402+0000] {subprocess.py:93} INFO - #19 0x55cd861e0666 <unknown>
[2023-12-21T14:38:12.404+0000] {subprocess.py:93} INFO - #20 0x55cd861b99ea <unknown>
[2023-12-21T14:38:12.407+0000] {subprocess.py:93} INFO - #21 0x55cd861f9689 <unknown>
[2023-12-21T14:38:12.409+0000] {subprocess.py:93} INFO - #22 0x55cd861f986f <unknown>
[2023-12-21T14:38:12.410+0000] {subprocess.py:93} INFO - #23 0x55cd86208173 <unknown>
[2023-12-21T14:38:12.413+0000] {subprocess.py:93} INFO - #24 0x7f444c3193ec <unknown>
[2023-12-21T14:38:12.414+0000] {subprocess.py:93} INFO - 
[2023-12-21T14:38:12.418+0000] {subprocess.py:93} INFO - 
[2023-12-21T14:38:12.419+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2023-12-21T14:38:12.421+0000] {subprocess.py:93} INFO - 
[2023-12-21T14:38:12.424+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T14:38:12.426+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/apps/crawler.py", line 78, in <module>
[2023-12-21T14:38:12.427+0000] {subprocess.py:93} INFO -     if driver.find_element(By.XPATH, f'//*[@id="main-content"]/section[2]/button').text == 'Ver mais vagas':
[2023-12-21T14:38:12.429+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 741, in find_element
[2023-12-21T14:38:12.430+0000] {subprocess.py:93} INFO -     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
[2023-12-21T14:38:12.433+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
[2023-12-21T14:38:12.435+0000] {subprocess.py:93} INFO -     self.error_handler.check_response(response)
[2023-12-21T14:38:12.436+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2023-12-21T14:38:12.439+0000] {subprocess.py:93} INFO -     raise exception_class(message, screen, stacktrace)
[2023-12-21T14:38:12.445+0000] {subprocess.py:93} INFO - selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
[2023-12-21T14:38:12.447+0000] {subprocess.py:93} INFO - Stacktrace:
[2023-12-21T14:38:12.450+0000] {subprocess.py:93} INFO - #0 0x55cd86208c07 <unknown>
[2023-12-21T14:38:12.453+0000] {subprocess.py:93} INFO - #1 0x55cd85eecd4a <unknown>
[2023-12-21T14:38:12.455+0000] {subprocess.py:93} INFO - #2 0x55cd85f24825 <unknown>
[2023-12-21T14:38:12.457+0000] {subprocess.py:93} INFO - #3 0x55cd85f26266 <unknown>
[2023-12-21T14:38:12.459+0000] {subprocess.py:93} INFO - #4 0x55cd861dcc00 <unknown>
[2023-12-21T14:38:12.460+0000] {subprocess.py:93} INFO - #5 0x55cd861dfdad <unknown>
[2023-12-21T14:38:12.461+0000] {subprocess.py:93} INFO - #6 0x55cd861df84a <unknown>
[2023-12-21T14:38:12.463+0000] {subprocess.py:93} INFO - #7 0x55cd861e02c9 <unknown>
[2023-12-21T14:38:12.464+0000] {subprocess.py:93} INFO - #8 0x55cd861e67e3 <unknown>
[2023-12-21T14:38:12.465+0000] {subprocess.py:93} INFO - #9 0x55cd861e0666 <unknown>
[2023-12-21T14:38:12.467+0000] {subprocess.py:93} INFO - #10 0x55cd861b99ea <unknown>
[2023-12-21T14:38:12.468+0000] {subprocess.py:93} INFO - #11 0x55cd861f9689 <unknown>
[2023-12-21T14:38:12.469+0000] {subprocess.py:93} INFO - #12 0x55cd861f986f <unknown>
[2023-12-21T14:38:12.470+0000] {subprocess.py:93} INFO - #13 0x55cd86208173 <unknown>
[2023-12-21T14:38:12.474+0000] {subprocess.py:93} INFO - #14 0x7f444c3193ec <unknown>
[2023-12-21T14:38:12.475+0000] {subprocess.py:93} INFO - 
[2023-12-21T14:38:12.477+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-21T14:38:12.503+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-21T14:38:12.512+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scraping-jobs, task_id=test***, execution_date=20231221T132303, start_date=20231221T143803, end_date=20231221T143812
[2023-12-21T14:38:12.564+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 20 for task test*** (Bash command failed. The command returned a non-zero exit code 1.; 551)
[2023-12-21T14:38:12.610+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T14:38:12.667+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
