[2023-12-21T14:35:45.624+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T13:23:03.607351+00:00/task_id=test*** permission to 509
[2023-12-21T14:35:45.627+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T13:23:03.607351+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T13:23:03.607351+00:00/task_id=test***'
[2023-12-21T14:35:45.832+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T13:23:03.607351+00:00/task_id=test*** permission to 509
[2023-12-21T14:35:45.880+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T13:23:03.607351+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T13:23:03.607351+00:00/task_id=test***'
[2023-12-21T14:35:46.107+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T13:23:03.607351+00:00 [queued]>
[2023-12-21T14:35:46.183+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T13:23:03.607351+00:00 [queued]>
[2023-12-21T14:35:46.188+0000] {taskinstance.py:1361} INFO - Starting attempt 8 of 8
[2023-12-21T14:35:46.350+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): testairflow> on 2023-12-21 13:23:03.607351+00:00
[2023-12-21T14:35:46.372+0000] {standard_task_runner.py:57} INFO - Started process 514 to run task
[2023-12-21T14:35:46.389+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraping-jobs', 'test***', 'manual__2023-12-21T13:23:03.607351+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dag-webscrappinglinkedin.py', '--cfg-path', '/tmp/tmpod1ljqeg']
[2023-12-21T14:35:46.392+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask test***
[2023-12-21T14:35:47.159+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T13:23:03.607351+00:00/task_id=test*** permission to 509
[2023-12-21T14:35:47.180+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T13:23:03.607351+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T13:23:03.607351+00:00/task_id=test***'
[2023-12-21T14:35:47.392+0000] {task_command.py:416} INFO - Running <TaskInstance: scraping-jobs.testairflow manual__2023-12-21T13:23:03.607351+00:00 [running]> on host ae1e32dc581d
[2023-12-21T14:35:48.687+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping-jobs' AIRFLOW_CTX_TASK_ID='test***' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T13:23:03.607351+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T13:23:03.607351+00:00'
[2023-12-21T14:35:48.844+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T14:35:49.007+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/apps/crawler.py']
[2023-12-21T14:35:49.228+0000] {subprocess.py:86} INFO - Output:
[2023-12-21T14:36:07.726+0000] {subprocess.py:93} INFO - Scrolling page...
[2023-12-21T14:36:07.876+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T14:36:07.881+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/apps/crawler.py", line 66, in <module>
[2023-12-21T14:36:07.891+0000] {subprocess.py:93} INFO -     job_description = WebDriverWait(driver, 2).until(EC.presence_of_element_located((By.XPATH, f'//*[@id="main-content"]/section[2]/ul/li[{n}]/div'))).text
[2023-12-21T14:36:07.893+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 92, in until
[2023-12-21T14:36:07.894+0000] {subprocess.py:93} INFO -     value = method(self._driver)
[2023-12-21T14:36:07.897+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py", line 80, in _predicate
[2023-12-21T14:36:07.907+0000] {subprocess.py:93} INFO -     return driver.find_element(*locator)
[2023-12-21T14:36:07.909+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 741, in find_element
[2023-12-21T14:36:07.911+0000] {subprocess.py:93} INFO -     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
[2023-12-21T14:36:07.912+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
[2023-12-21T14:36:07.915+0000] {subprocess.py:93} INFO -     self.error_handler.check_response(response)
[2023-12-21T14:36:07.916+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2023-12-21T14:36:07.921+0000] {subprocess.py:93} INFO -     raise exception_class(message, screen, stacktrace)
[2023-12-21T14:36:07.923+0000] {subprocess.py:93} INFO - selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
[2023-12-21T14:36:07.924+0000] {subprocess.py:93} INFO - from unknown error: cannot determine loading status
[2023-12-21T14:36:07.953+0000] {subprocess.py:93} INFO - from tab crashed
[2023-12-21T14:36:07.961+0000] {subprocess.py:93} INFO -   (Session info: headless chrome=117.0.5938.62)
[2023-12-21T14:36:07.972+0000] {subprocess.py:93} INFO - Stacktrace:
[2023-12-21T14:36:07.975+0000] {subprocess.py:93} INFO - #0 0x559458126c07 <unknown>
[2023-12-21T14:36:07.978+0000] {subprocess.py:93} INFO - #1 0x559457e0ad4a <unknown>
[2023-12-21T14:36:07.980+0000] {subprocess.py:93} INFO - #2 0x559457df6733 <unknown>
[2023-12-21T14:36:07.982+0000] {subprocess.py:93} INFO - #3 0x559457df5678 <unknown>
[2023-12-21T14:36:07.983+0000] {subprocess.py:93} INFO - #4 0x559457df5c7d <unknown>
[2023-12-21T14:36:07.984+0000] {subprocess.py:93} INFO - #5 0x559457e02dd8 <unknown>
[2023-12-21T14:36:07.986+0000] {subprocess.py:93} INFO - #6 0x559457e15703 <unknown>
[2023-12-21T14:36:07.987+0000] {subprocess.py:93} INFO - #7 0x559457e198bf <unknown>
[2023-12-21T14:36:07.997+0000] {subprocess.py:93} INFO - #8 0x559457df614e <unknown>
[2023-12-21T14:36:07.999+0000] {subprocess.py:93} INFO - #9 0x559457e153e6 <unknown>
[2023-12-21T14:36:08.000+0000] {subprocess.py:93} INFO - #10 0x559457e84413 <unknown>
[2023-12-21T14:36:08.018+0000] {subprocess.py:93} INFO - #11 0x559457e6d9b7 <unknown>
[2023-12-21T14:36:08.029+0000] {subprocess.py:93} INFO - #12 0x559457e42cad <unknown>
[2023-12-21T14:36:08.057+0000] {subprocess.py:93} INFO - #13 0x559457e44266 <unknown>
[2023-12-21T14:36:08.069+0000] {subprocess.py:93} INFO - #14 0x5594580fac00 <unknown>
[2023-12-21T14:36:08.073+0000] {subprocess.py:93} INFO - #15 0x5594580fddad <unknown>
[2023-12-21T14:36:08.079+0000] {subprocess.py:93} INFO - #16 0x5594580fd84a <unknown>
[2023-12-21T14:36:08.087+0000] {subprocess.py:93} INFO - #17 0x5594580fe2c9 <unknown>
[2023-12-21T14:36:08.091+0000] {subprocess.py:93} INFO - #18 0x5594581047e3 <unknown>
[2023-12-21T14:36:08.093+0000] {subprocess.py:93} INFO - #19 0x5594580fe666 <unknown>
[2023-12-21T14:36:08.094+0000] {subprocess.py:93} INFO - #20 0x5594580d79ea <unknown>
[2023-12-21T14:36:08.097+0000] {subprocess.py:93} INFO - #21 0x559458117689 <unknown>
[2023-12-21T14:36:08.099+0000] {subprocess.py:93} INFO - #22 0x55945811786f <unknown>
[2023-12-21T14:36:08.100+0000] {subprocess.py:93} INFO - #23 0x559458126173 <unknown>
[2023-12-21T14:36:08.102+0000] {subprocess.py:93} INFO - #24 0x7f7de94483ec <unknown>
[2023-12-21T14:36:08.105+0000] {subprocess.py:93} INFO - 
[2023-12-21T14:36:08.108+0000] {subprocess.py:93} INFO - 
[2023-12-21T14:36:08.109+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2023-12-21T14:36:08.111+0000] {subprocess.py:93} INFO - 
[2023-12-21T14:36:08.114+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T14:36:08.116+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/apps/crawler.py", line 78, in <module>
[2023-12-21T14:36:08.118+0000] {subprocess.py:93} INFO -     if driver.find_element(By.XPATH, f'//*[@id="main-content"]/section[2]/button').text == 'Ver mais vagas':
[2023-12-21T14:36:08.121+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 741, in find_element
[2023-12-21T14:36:08.124+0000] {subprocess.py:93} INFO -     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
[2023-12-21T14:36:08.125+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
[2023-12-21T14:36:08.127+0000] {subprocess.py:93} INFO -     self.error_handler.check_response(response)
[2023-12-21T14:36:08.130+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2023-12-21T14:36:08.131+0000] {subprocess.py:93} INFO -     raise exception_class(message, screen, stacktrace)
[2023-12-21T14:36:08.132+0000] {subprocess.py:93} INFO - selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
[2023-12-21T14:36:08.134+0000] {subprocess.py:93} INFO - Stacktrace:
[2023-12-21T14:36:08.140+0000] {subprocess.py:93} INFO - #0 0x559458126c07 <unknown>
[2023-12-21T14:36:08.202+0000] {subprocess.py:93} INFO - #1 0x559457e0ad4a <unknown>
[2023-12-21T14:36:08.244+0000] {subprocess.py:93} INFO - #2 0x559457e4245d <unknown>
[2023-12-21T14:36:08.267+0000] {subprocess.py:93} INFO - #3 0x559457e6db1a <unknown>
[2023-12-21T14:36:08.270+0000] {subprocess.py:93} INFO - #4 0x559457e69b67 <unknown>
[2023-12-21T14:36:08.282+0000] {subprocess.py:93} INFO - #5 0x559457e692a7 <unknown>
[2023-12-21T14:36:08.284+0000] {subprocess.py:93} INFO - #6 0x559457ddd9d7 <unknown>
[2023-12-21T14:36:08.286+0000] {subprocess.py:93} INFO - #7 0x5594580fac00 <unknown>
[2023-12-21T14:36:08.289+0000] {subprocess.py:93} INFO - #8 0x5594580fddad <unknown>
[2023-12-21T14:36:08.290+0000] {subprocess.py:93} INFO - #9 0x5594580fd84a <unknown>
[2023-12-21T14:36:08.292+0000] {subprocess.py:93} INFO - #10 0x5594580fe2c9 <unknown>
[2023-12-21T14:36:08.294+0000] {subprocess.py:93} INFO - #11 0x5594581047e3 <unknown>
[2023-12-21T14:36:08.303+0000] {subprocess.py:93} INFO - #12 0x5594580fe666 <unknown>
[2023-12-21T14:36:08.306+0000] {subprocess.py:93} INFO - #13 0x5594580d79ea <unknown>
[2023-12-21T14:36:08.307+0000] {subprocess.py:93} INFO - #14 0x559457ddc28e <unknown>
[2023-12-21T14:36:08.315+0000] {subprocess.py:93} INFO - #15 0x559457ddba62 <unknown>
[2023-12-21T14:36:08.317+0000] {subprocess.py:93} INFO - #16 0x7f7de93e76ca <unknown>
[2023-12-21T14:36:08.323+0000] {subprocess.py:93} INFO - 
[2023-12-21T14:36:08.324+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-21T14:36:08.374+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-21T14:36:08.392+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scraping-jobs, task_id=test***, execution_date=20231221T132303, start_date=20231221T143546, end_date=20231221T143608
[2023-12-21T14:36:08.495+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task test*** (Bash command failed. The command returned a non-zero exit code 1.; 514)
[2023-12-21T14:36:08.590+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T14:36:08.656+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
