[2023-12-21T16:13:49.456+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:13:45.318435+00:00/task_id=test*** permission to 509
[2023-12-21T16:13:49.458+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:13:45.318435+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:13:45.318435+00:00/task_id=test***'
[2023-12-21T16:13:49.562+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:13:45.318435+00:00/task_id=test*** permission to 509
[2023-12-21T16:13:49.565+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:13:45.318435+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:13:45.318435+00:00/task_id=test***'
[2023-12-21T16:13:49.693+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T16:13:45.318435+00:00 [queued]>
[2023-12-21T16:13:49.736+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T16:13:45.318435+00:00 [queued]>
[2023-12-21T16:13:49.738+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-21T16:13:49.798+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): testairflow> on 2023-12-21 16:13:45.318435+00:00
[2023-12-21T16:13:49.822+0000] {standard_task_runner.py:57} INFO - Started process 597 to run task
[2023-12-21T16:13:49.826+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraping-jobs', 'test***', 'manual__2023-12-21T16:13:45.318435+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/webscrapinglinkedin/dag-webscrapinglinkedin.py', '--cfg-path', '/tmp/tmpk0n5_l3f']
[2023-12-21T16:13:49.838+0000] {standard_task_runner.py:85} INFO - Job 57: Subtask test***
[2023-12-21T16:13:49.977+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:13:45.318435+00:00/task_id=test*** permission to 509
[2023-12-21T16:13:49.978+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:13:45.318435+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:13:45.318435+00:00/task_id=test***'
[2023-12-21T16:13:49.986+0000] {task_command.py:416} INFO - Running <TaskInstance: scraping-jobs.testairflow manual__2023-12-21T16:13:45.318435+00:00 [running]> on host cdaea2bd355d
[2023-12-21T16:13:50.197+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping-jobs' AIRFLOW_CTX_TASK_ID='test***' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T16:13:45.318435+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T16:13:45.318435+00:00'
[2023-12-21T16:13:50.199+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T16:13:50.202+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/webscrapinglinkedin/crawler.py']
[2023-12-21T16:13:50.224+0000] {subprocess.py:86} INFO - Output:
[2023-12-21T16:13:54.688+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T16:13:54.689+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/webscrapinglinkedin/crawler.py", line 62, in <module>
[2023-12-21T16:13:54.690+0000] {subprocess.py:93} INFO -     driver.execute_script("window.scrollTo(0, document.body.scrollHeight)")
[2023-12-21T16:13:54.691+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 407, in execute_script
[2023-12-21T16:13:54.692+0000] {subprocess.py:93} INFO -     return self.execute(command, {"script": script, "args": converted_args})["value"]
[2023-12-21T16:13:54.693+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
[2023-12-21T16:13:54.694+0000] {subprocess.py:93} INFO -     self.error_handler.check_response(response)
[2023-12-21T16:13:54.697+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2023-12-21T16:13:54.699+0000] {subprocess.py:93} INFO -     raise exception_class(message, screen, stacktrace)
[2023-12-21T16:13:54.702+0000] {subprocess.py:93} INFO - selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read properties of null (reading 'scrollHeight')
[2023-12-21T16:13:54.703+0000] {subprocess.py:93} INFO -   (Session info: headless chrome=117.0.5938.62)
[2023-12-21T16:13:54.707+0000] {subprocess.py:93} INFO - Stacktrace:
[2023-12-21T16:13:54.708+0000] {subprocess.py:93} INFO - #0 0x5586de865c07 <unknown>
[2023-12-21T16:13:54.709+0000] {subprocess.py:93} INFO - #1 0x5586de54a03c <unknown>
[2023-12-21T16:13:54.710+0000] {subprocess.py:93} INFO - #2 0x5586de54f070 <unknown>
[2023-12-21T16:13:54.711+0000] {subprocess.py:93} INFO - #3 0x5586de5507de <unknown>
[2023-12-21T16:13:54.717+0000] {subprocess.py:93} INFO - #4 0x5586de5c3f86 <unknown>
[2023-12-21T16:13:54.719+0000] {subprocess.py:93} INFO - #5 0x5586de5acc26 <unknown>
[2023-12-21T16:13:54.720+0000] {subprocess.py:93} INFO - #6 0x5586de5c34e5 <unknown>
[2023-12-21T16:13:54.721+0000] {subprocess.py:93} INFO - #7 0x5586de5ac9b7 <unknown>
[2023-12-21T16:13:54.722+0000] {subprocess.py:93} INFO - #8 0x5586de581cad <unknown>
[2023-12-21T16:13:54.724+0000] {subprocess.py:93} INFO - #9 0x5586de583266 <unknown>
[2023-12-21T16:13:54.725+0000] {subprocess.py:93} INFO - #10 0x5586de839c00 <unknown>
[2023-12-21T16:13:54.726+0000] {subprocess.py:93} INFO - #11 0x5586de83cdad <unknown>
[2023-12-21T16:13:54.727+0000] {subprocess.py:93} INFO - #12 0x5586de83c84a <unknown>
[2023-12-21T16:13:54.730+0000] {subprocess.py:93} INFO - #13 0x5586de83d2c9 <unknown>
[2023-12-21T16:13:54.731+0000] {subprocess.py:93} INFO - #14 0x5586de8437e3 <unknown>
[2023-12-21T16:13:54.732+0000] {subprocess.py:93} INFO - #15 0x5586de83d666 <unknown>
[2023-12-21T16:13:54.734+0000] {subprocess.py:93} INFO - #16 0x5586de8169ea <unknown>
[2023-12-21T16:13:54.735+0000] {subprocess.py:93} INFO - #17 0x5586de856689 <unknown>
[2023-12-21T16:13:54.736+0000] {subprocess.py:93} INFO - #18 0x5586de85686f <unknown>
[2023-12-21T16:13:54.737+0000] {subprocess.py:93} INFO - #19 0x5586de865173 <unknown>
[2023-12-21T16:13:54.738+0000] {subprocess.py:93} INFO - #20 0x7f9ee3b903ec <unknown>
[2023-12-21T16:13:54.739+0000] {subprocess.py:93} INFO - 
[2023-12-21T16:13:54.741+0000] {subprocess.py:93} INFO - 
[2023-12-21T16:13:54.742+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2023-12-21T16:13:54.743+0000] {subprocess.py:93} INFO - 
[2023-12-21T16:13:54.744+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T16:13:54.748+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/webscrapinglinkedin/crawler.py", line 80, in <module>
[2023-12-21T16:13:54.750+0000] {subprocess.py:93} INFO -     if driver.find_element(By.XPATH, f'//*[@id="main-content"]/section[2]/button').text == 'Ver mais vagas':
[2023-12-21T16:13:54.751+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 741, in find_element
[2023-12-21T16:13:54.753+0000] {subprocess.py:93} INFO -     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
[2023-12-21T16:13:54.754+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
[2023-12-21T16:13:54.755+0000] {subprocess.py:93} INFO -     self.error_handler.check_response(response)
[2023-12-21T16:13:54.756+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2023-12-21T16:13:54.758+0000] {subprocess.py:93} INFO -     raise exception_class(message, screen, stacktrace)
[2023-12-21T16:13:54.759+0000] {subprocess.py:93} INFO - selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="main-content"]/section[2]/button"}
[2023-12-21T16:13:54.760+0000] {subprocess.py:93} INFO -   (Session info: headless chrome=117.0.5938.62); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
[2023-12-21T16:13:54.804+0000] {subprocess.py:93} INFO - Stacktrace:
[2023-12-21T16:13:54.805+0000] {subprocess.py:93} INFO - #0 0x5586de865c07 <unknown>
[2023-12-21T16:13:54.806+0000] {subprocess.py:93} INFO - #1 0x5586de54a03c <unknown>
[2023-12-21T16:13:54.807+0000] {subprocess.py:93} INFO - #2 0x5586de58d222 <unknown>
[2023-12-21T16:13:54.826+0000] {subprocess.py:93} INFO - #3 0x5586de58d345 <unknown>
[2023-12-21T16:13:54.828+0000] {subprocess.py:93} INFO - #4 0x5586de5c5668 <unknown>
[2023-12-21T16:13:54.830+0000] {subprocess.py:93} INFO - #5 0x5586de5acc51 <unknown>
[2023-12-21T16:13:54.832+0000] {subprocess.py:93} INFO - #6 0x5586de5c34e5 <unknown>
[2023-12-21T16:13:54.833+0000] {subprocess.py:93} INFO - #7 0x5586de5ac9b7 <unknown>
[2023-12-21T16:13:54.834+0000] {subprocess.py:93} INFO - #8 0x5586de581cad <unknown>
[2023-12-21T16:13:54.835+0000] {subprocess.py:93} INFO - #9 0x5586de583266 <unknown>
[2023-12-21T16:13:54.836+0000] {subprocess.py:93} INFO - #10 0x5586de839c00 <unknown>
[2023-12-21T16:13:54.837+0000] {subprocess.py:93} INFO - #11 0x5586de83cdad <unknown>
[2023-12-21T16:13:54.838+0000] {subprocess.py:93} INFO - #12 0x5586de83c84a <unknown>
[2023-12-21T16:13:54.839+0000] {subprocess.py:93} INFO - #13 0x5586de83d2c9 <unknown>
[2023-12-21T16:13:54.840+0000] {subprocess.py:93} INFO - #14 0x5586de8437e3 <unknown>
[2023-12-21T16:13:54.841+0000] {subprocess.py:93} INFO - #15 0x5586de83d666 <unknown>
[2023-12-21T16:13:54.842+0000] {subprocess.py:93} INFO - #16 0x5586de8169ea <unknown>
[2023-12-21T16:13:54.843+0000] {subprocess.py:93} INFO - #17 0x5586de856689 <unknown>
[2023-12-21T16:13:54.844+0000] {subprocess.py:93} INFO - #18 0x5586de85686f <unknown>
[2023-12-21T16:13:54.845+0000] {subprocess.py:93} INFO - #19 0x5586de865173 <unknown>
[2023-12-21T16:13:54.847+0000] {subprocess.py:93} INFO - #20 0x7f9ee3b903ec <unknown>
[2023-12-21T16:13:54.848+0000] {subprocess.py:93} INFO - 
[2023-12-21T16:13:54.849+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-21T16:13:54.866+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-21T16:13:54.872+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scraping-jobs, task_id=test***, execution_date=20231221T161345, start_date=20231221T161349, end_date=20231221T161354
[2023-12-21T16:13:54.904+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 57 for task test*** (Bash command failed. The command returned a non-zero exit code 1.; 597)
[2023-12-21T16:13:54.928+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T16:13:54.956+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
