[2023-12-21T16:04:37.909+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test*** permission to 509
[2023-12-21T16:04:37.911+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test***'
[2023-12-21T16:04:37.960+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test*** permission to 509
[2023-12-21T16:04:37.961+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test***'
[2023-12-21T16:04:38.011+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T16:04:34.746900+00:00 [queued]>
[2023-12-21T16:04:38.026+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T16:04:34.746900+00:00 [queued]>
[2023-12-21T16:04:38.027+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-21T16:04:38.049+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): testairflow> on 2023-12-21 16:04:34.746900+00:00
[2023-12-21T16:04:38.058+0000] {standard_task_runner.py:57} INFO - Started process 450 to run task
[2023-12-21T16:04:38.062+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraping-jobs', 'test***', 'manual__2023-12-21T16:04:34.746900+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/webscrapinglinkedin/dag-webscrapinglinkedin.py', '--cfg-path', '/tmp/tmp9sx2pym_']
[2023-12-21T16:04:38.064+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask test***
[2023-12-21T16:04:38.154+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test*** permission to 509
[2023-12-21T16:04:38.156+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test***'
[2023-12-21T16:04:38.164+0000] {task_command.py:416} INFO - Running <TaskInstance: scraping-jobs.testairflow manual__2023-12-21T16:04:34.746900+00:00 [running]> on host cdaea2bd355d
[2023-12-21T16:04:38.305+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping-jobs' AIRFLOW_CTX_TASK_ID='test***' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T16:04:34.746900+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T16:04:34.746900+00:00'
[2023-12-21T16:04:38.307+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T16:04:38.309+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/webscrapinglinkedin/browser.py']
[2023-12-21T16:04:38.327+0000] {subprocess.py:86} INFO - Output:
[2023-12-21T16:04:40.693+0000] {subprocess.py:93} INFO - INFO:root:Has opened chrome.
[2023-12-21T16:04:40.722+0000] {subprocess.py:93} INFO - INFO:root:Has search jobs.
[2023-12-21T16:04:40.838+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T16:04:40.840+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/webscrapinglinkedin/browser.py", line 39, in <module>
[2023-12-21T16:04:40.841+0000] {subprocess.py:93} INFO -     driver.get(url)
[2023-12-21T16:04:40.851+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
[2023-12-21T16:04:40.853+0000] {subprocess.py:93} INFO -     self.execute(Command.GET, {"url": url})
[2023-12-21T16:04:40.854+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
[2023-12-21T16:04:40.856+0000] {subprocess.py:93} INFO -     self.error_handler.check_response(response)
[2023-12-21T16:04:40.859+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2023-12-21T16:04:40.861+0000] {subprocess.py:93} INFO -     raise exception_class(message, screen, stacktrace)
[2023-12-21T16:04:40.863+0000] {subprocess.py:93} INFO - selenium.common.exceptions.InvalidSessionIdException: Message: Unable to execute request for an existing session: Unable to find session with ID: 03d19f941e964a416f9a9482621dd2c8
[2023-12-21T16:04:40.878+0000] {subprocess.py:93} INFO - Build info: version: '4.10.0', revision: 'c14d967899'
[2023-12-21T16:04:40.943+0000] {subprocess.py:93} INFO - System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.20'
[2023-12-21T16:04:40.981+0000] {subprocess.py:93} INFO - Driver info: driver.version: unknown
[2023-12-21T16:04:41.295+0000] {subprocess.py:93} INFO - 
[2023-12-21T16:04:41.398+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-21T16:04:41.453+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-21T16:04:41.473+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scraping-jobs, task_id=test***, execution_date=20231221T160434, start_date=20231221T160438, end_date=20231221T160441
[2023-12-21T16:04:41.547+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 53 for task test*** (Bash command failed. The command returned a non-zero exit code 1.; 450)
[2023-12-21T16:04:41.634+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T16:04:41.727+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
