[2023-12-21T16:10:08.875+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test*** permission to 509
[2023-12-21T16:10:08.877+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test***'
[2023-12-21T16:10:08.922+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test*** permission to 509
[2023-12-21T16:10:08.924+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test***'
[2023-12-21T16:10:08.974+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T16:04:34.746900+00:00 [queued]>
[2023-12-21T16:10:08.989+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T16:04:34.746900+00:00 [queued]>
[2023-12-21T16:10:08.990+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-12-21T16:10:09.013+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): testairflow> on 2023-12-21 16:04:34.746900+00:00
[2023-12-21T16:10:09.021+0000] {standard_task_runner.py:57} INFO - Started process 544 to run task
[2023-12-21T16:10:09.026+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraping-jobs', 'test***', 'manual__2023-12-21T16:04:34.746900+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/webscrapinglinkedin/dag-webscrapinglinkedin.py', '--cfg-path', '/tmp/tmpvvo97q1v']
[2023-12-21T16:10:09.028+0000] {standard_task_runner.py:85} INFO - Job 56: Subtask test***
[2023-12-21T16:10:09.126+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test*** permission to 509
[2023-12-21T16:10:09.127+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test***'
[2023-12-21T16:10:09.132+0000] {task_command.py:416} INFO - Running <TaskInstance: scraping-jobs.testairflow manual__2023-12-21T16:04:34.746900+00:00 [running]> on host cdaea2bd355d
[2023-12-21T16:10:09.256+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping-jobs' AIRFLOW_CTX_TASK_ID='test***' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T16:04:34.746900+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T16:04:34.746900+00:00'
[2023-12-21T16:10:09.264+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T16:10:09.266+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/webscrapinglinkedin/browser.py']
[2023-12-21T16:10:09.283+0000] {subprocess.py:86} INFO - Output:
[2023-12-21T16:10:11.189+0000] {subprocess.py:93} INFO - INFO:root:Has opened chrome.
[2023-12-21T16:10:11.191+0000] {subprocess.py:93} INFO - INFO:root:Has search jobs.
[2023-12-21T16:10:11.224+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T16:10:11.228+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/webscrapinglinkedin/browser.py", line 38, in <module>
[2023-12-21T16:10:11.229+0000] {subprocess.py:93} INFO -     driver.get(url)
[2023-12-21T16:10:11.231+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
[2023-12-21T16:10:11.232+0000] {subprocess.py:93} INFO -     self.execute(Command.GET, {"url": url})
[2023-12-21T16:10:11.233+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
[2023-12-21T16:10:11.234+0000] {subprocess.py:93} INFO -     self.error_handler.check_response(response)
[2023-12-21T16:10:11.234+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2023-12-21T16:10:11.236+0000] {subprocess.py:93} INFO -     raise exception_class(message, screen, stacktrace)
[2023-12-21T16:10:11.238+0000] {subprocess.py:93} INFO - selenium.common.exceptions.InvalidSessionIdException: Message: Unable to execute request for an existing session: Unable to find session with ID: ddbdc6d8948e3bc20e348e95da024adc
[2023-12-21T16:10:11.239+0000] {subprocess.py:93} INFO - Build info: version: '4.10.0', revision: 'c14d967899'
[2023-12-21T16:10:11.241+0000] {subprocess.py:93} INFO - System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.20'
[2023-12-21T16:10:11.242+0000] {subprocess.py:93} INFO - Driver info: driver.version: unknown
[2023-12-21T16:10:11.243+0000] {subprocess.py:93} INFO - 
[2023-12-21T16:10:11.261+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-21T16:10:11.277+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-21T16:10:11.283+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scraping-jobs, task_id=test***, execution_date=20231221T160434, start_date=20231221T161008, end_date=20231221T161011
[2023-12-21T16:10:11.306+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 56 for task test*** (Bash command failed. The command returned a non-zero exit code 1.; 544)
[2023-12-21T16:10:11.333+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T16:10:11.360+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
