[2023-12-21T16:08:49.877+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test*** permission to 509
[2023-12-21T16:08:49.879+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test***'
[2023-12-21T16:08:49.932+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test*** permission to 509
[2023-12-21T16:08:49.936+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test***'
[2023-12-21T16:08:49.988+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T16:04:34.746900+00:00 [queued]>
[2023-12-21T16:08:50.004+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T16:04:34.746900+00:00 [queued]>
[2023-12-21T16:08:50.005+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2023-12-21T16:08:50.027+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): testairflow> on 2023-12-21 16:04:34.746900+00:00
[2023-12-21T16:08:50.036+0000] {standard_task_runner.py:57} INFO - Started process 514 to run task
[2023-12-21T16:08:50.041+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraping-jobs', 'test***', 'manual__2023-12-21T16:04:34.746900+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/webscrapinglinkedin/dag-webscrapinglinkedin.py', '--cfg-path', '/tmp/tmpdos__4au']
[2023-12-21T16:08:50.043+0000] {standard_task_runner.py:85} INFO - Job 55: Subtask test***
[2023-12-21T16:08:50.120+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test*** permission to 509
[2023-12-21T16:08:50.121+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T16:04:34.746900+00:00/task_id=test***'
[2023-12-21T16:08:50.126+0000] {task_command.py:416} INFO - Running <TaskInstance: scraping-jobs.testairflow manual__2023-12-21T16:04:34.746900+00:00 [running]> on host cdaea2bd355d
[2023-12-21T16:08:50.264+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping-jobs' AIRFLOW_CTX_TASK_ID='test***' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T16:04:34.746900+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T16:04:34.746900+00:00'
[2023-12-21T16:08:50.269+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T16:08:50.271+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/webscrapinglinkedin/browser.py']
[2023-12-21T16:08:50.291+0000] {subprocess.py:86} INFO - Output:
[2023-12-21T16:08:53.211+0000] {subprocess.py:93} INFO - INFO:root:Has opened chrome.
[2023-12-21T16:08:53.217+0000] {subprocess.py:93} INFO - INFO:root:Has search jobs.
[2023-12-21T16:08:53.410+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T16:08:53.412+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/webscrapinglinkedin/browser.py", line 38, in <module>
[2023-12-21T16:08:53.415+0000] {subprocess.py:93} INFO -     driver.get(url)
[2023-12-21T16:08:53.417+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
[2023-12-21T16:08:53.419+0000] {subprocess.py:93} INFO -     self.execute(Command.GET, {"url": url})
[2023-12-21T16:08:53.422+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
[2023-12-21T16:08:53.423+0000] {subprocess.py:93} INFO -     self.error_handler.check_response(response)
[2023-12-21T16:08:53.424+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2023-12-21T16:08:53.426+0000] {subprocess.py:93} INFO -     raise exception_class(message, screen, stacktrace)
[2023-12-21T16:08:53.427+0000] {subprocess.py:93} INFO - selenium.common.exceptions.InvalidSessionIdException: Message: Unable to execute request for an existing session: Unable to find session with ID: 04f5ab5819c8422833e46ee358ae3765
[2023-12-21T16:08:53.428+0000] {subprocess.py:93} INFO - Build info: version: '4.10.0', revision: 'c14d967899'
[2023-12-21T16:08:53.431+0000] {subprocess.py:93} INFO - System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.20'
[2023-12-21T16:08:53.432+0000] {subprocess.py:93} INFO - Driver info: driver.version: unknown
[2023-12-21T16:08:53.433+0000] {subprocess.py:93} INFO - 
[2023-12-21T16:08:53.460+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-21T16:08:53.484+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-21T16:08:53.489+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scraping-jobs, task_id=test***, execution_date=20231221T160434, start_date=20231221T160849, end_date=20231221T160853
[2023-12-21T16:08:53.516+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 55 for task test*** (Bash command failed. The command returned a non-zero exit code 1.; 514)
[2023-12-21T16:08:53.557+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T16:08:53.598+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
