[2023-12-21T15:55:43.256+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509
[2023-12-21T15:55:43.258+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test***'
[2023-12-21T15:55:43.307+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509
[2023-12-21T15:55:43.309+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test***'
[2023-12-21T15:55:43.372+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:53:24.607881+00:00 [queued]>
[2023-12-21T15:55:43.391+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:53:24.607881+00:00 [queued]>
[2023-12-21T15:55:43.391+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2023-12-21T15:55:43.416+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): testairflow> on 2023-12-21 15:53:24.607881+00:00
[2023-12-21T15:55:43.428+0000] {standard_task_runner.py:57} INFO - Started process 309 to run task
[2023-12-21T15:55:43.435+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraping-jobs', 'test***', 'manual__2023-12-21T15:53:24.607881+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/webscrapinglinkedin/dag-webscrapinglinkedin.py', '--cfg-path', '/tmp/tmpop4fye09']
[2023-12-21T15:55:43.437+0000] {standard_task_runner.py:85} INFO - Job 48: Subtask test***
[2023-12-21T15:55:43.557+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509
[2023-12-21T15:55:43.558+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test***'
[2023-12-21T15:55:43.565+0000] {task_command.py:416} INFO - Running <TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:53:24.607881+00:00 [running]> on host cdaea2bd355d
[2023-12-21T15:55:43.700+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping-jobs' AIRFLOW_CTX_TASK_ID='test***' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T15:53:24.607881+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T15:53:24.607881+00:00'
[2023-12-21T15:55:43.717+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T15:55:43.721+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/webscrapinglinkedin/aux-pedreiro.py']
[2023-12-21T15:55:43.737+0000] {subprocess.py:86} INFO - Output:
[2023-12-21T15:55:46.545+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T15:55:46.546+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/webscrapinglinkedin/aux-pedreiro.py", line 14, in <module>
[2023-12-21T15:55:46.547+0000] {subprocess.py:93} INFO -     driver.get(url)
[2023-12-21T15:55:46.549+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
[2023-12-21T15:55:46.551+0000] {subprocess.py:93} INFO -     self.execute(Command.GET, {"url": url})
[2023-12-21T15:55:46.553+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
[2023-12-21T15:55:46.554+0000] {subprocess.py:93} INFO -     self.error_handler.check_response(response)
[2023-12-21T15:55:46.555+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2023-12-21T15:55:46.556+0000] {subprocess.py:93} INFO -     raise exception_class(message, screen, stacktrace)
[2023-12-21T15:55:46.557+0000] {subprocess.py:93} INFO - selenium.common.exceptions.InvalidSessionIdException: Message: Unable to execute request for an existing session: Unable to find session with ID: 6a7a49cd5c222bc80f30557e6a1989f8
[2023-12-21T15:55:46.558+0000] {subprocess.py:93} INFO - Build info: version: '4.10.0', revision: 'c14d967899'
[2023-12-21T15:55:46.560+0000] {subprocess.py:93} INFO - System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.20'
[2023-12-21T15:55:46.561+0000] {subprocess.py:93} INFO - Driver info: driver.version: unknown
[2023-12-21T15:55:46.562+0000] {subprocess.py:93} INFO - 
[2023-12-21T15:55:46.581+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-21T15:55:46.599+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-21T15:55:46.608+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scraping-jobs, task_id=test***, execution_date=20231221T155324, start_date=20231221T155543, end_date=20231221T155546
[2023-12-21T15:55:46.630+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 48 for task test*** (Bash command failed. The command returned a non-zero exit code 1.; 309)
[2023-12-21T15:55:46.655+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T15:55:46.681+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
