[2023-12-21T15:56:35.529+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509
[2023-12-21T15:56:35.531+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test***'
[2023-12-21T15:56:35.585+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509
[2023-12-21T15:56:35.587+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test***'
[2023-12-21T15:56:35.645+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:53:24.607881+00:00 [queued]>
[2023-12-21T15:56:35.663+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:53:24.607881+00:00 [queued]>
[2023-12-21T15:56:35.664+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-12-21T15:56:35.692+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): testairflow> on 2023-12-21 15:53:24.607881+00:00
[2023-12-21T15:56:35.700+0000] {standard_task_runner.py:57} INFO - Started process 321 to run task
[2023-12-21T15:56:35.707+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraping-jobs', 'test***', 'manual__2023-12-21T15:53:24.607881+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/webscrapinglinkedin/dag-webscrapinglinkedin.py', '--cfg-path', '/tmp/tmp3bkq3j5u']
[2023-12-21T15:56:35.710+0000] {standard_task_runner.py:85} INFO - Job 49: Subtask test***
[2023-12-21T15:56:35.808+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509
[2023-12-21T15:56:35.810+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test***'
[2023-12-21T15:56:35.815+0000] {task_command.py:416} INFO - Running <TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:53:24.607881+00:00 [running]> on host cdaea2bd355d
[2023-12-21T15:56:36.069+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping-jobs' AIRFLOW_CTX_TASK_ID='test***' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T15:53:24.607881+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T15:53:24.607881+00:00'
[2023-12-21T15:56:36.075+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T15:56:36.077+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/webscrapinglinkedin/crawler.py']
[2023-12-21T15:56:36.113+0000] {subprocess.py:86} INFO - Output:
[2023-12-21T15:56:41.878+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T15:56:41.886+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/webscrapinglinkedin/crawler.py", line 60, in <module>
[2023-12-21T15:56:41.888+0000] {subprocess.py:93} INFO -     driver.execute_script("window.scrollTo(0, document.body.scrollHeight)")
[2023-12-21T15:56:41.890+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 407, in execute_script
[2023-12-21T15:56:41.891+0000] {subprocess.py:93} INFO -     return self.execute(command, {"script": script, "args": converted_args})["value"]
[2023-12-21T15:56:41.892+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
[2023-12-21T15:56:41.893+0000] {subprocess.py:93} INFO -     self.error_handler.check_response(response)
[2023-12-21T15:56:41.893+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2023-12-21T15:56:41.900+0000] {subprocess.py:93} INFO -     raise exception_class(message, screen, stacktrace)
[2023-12-21T15:56:41.901+0000] {subprocess.py:93} INFO - selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read properties of null (reading 'scrollHeight')
[2023-12-21T15:56:41.902+0000] {subprocess.py:93} INFO -   (Session info: headless chrome=117.0.5938.62)
[2023-12-21T15:56:41.903+0000] {subprocess.py:93} INFO - Stacktrace:
[2023-12-21T15:56:41.904+0000] {subprocess.py:93} INFO - #0 0x55e75276fc07 <unknown>
[2023-12-21T15:56:41.905+0000] {subprocess.py:93} INFO - #1 0x55e75245403c <unknown>
[2023-12-21T15:56:41.906+0000] {subprocess.py:93} INFO - #2 0x55e752459070 <unknown>
[2023-12-21T15:56:41.908+0000] {subprocess.py:93} INFO - #3 0x55e75245a7de <unknown>
[2023-12-21T15:56:41.909+0000] {subprocess.py:93} INFO - #4 0x55e7524cdf86 <unknown>
[2023-12-21T15:56:41.910+0000] {subprocess.py:93} INFO - #5 0x55e7524b6c26 <unknown>
[2023-12-21T15:56:41.916+0000] {subprocess.py:93} INFO - #6 0x55e7524cd4e5 <unknown>
[2023-12-21T15:56:41.921+0000] {subprocess.py:93} INFO - #7 0x55e7524b69b7 <unknown>
[2023-12-21T15:56:41.922+0000] {subprocess.py:93} INFO - #8 0x55e75248bcad <unknown>
[2023-12-21T15:56:41.925+0000] {subprocess.py:93} INFO - #9 0x55e75248d266 <unknown>
[2023-12-21T15:56:41.926+0000] {subprocess.py:93} INFO - #10 0x55e752743c00 <unknown>
[2023-12-21T15:56:41.929+0000] {subprocess.py:93} INFO - #11 0x55e752746dad <unknown>
[2023-12-21T15:56:41.931+0000] {subprocess.py:93} INFO - #12 0x55e75274684a <unknown>
[2023-12-21T15:56:41.932+0000] {subprocess.py:93} INFO - #13 0x55e7527472c9 <unknown>
[2023-12-21T15:56:41.934+0000] {subprocess.py:93} INFO - #14 0x55e75274d7e3 <unknown>
[2023-12-21T15:56:41.935+0000] {subprocess.py:93} INFO - #15 0x55e752747666 <unknown>
[2023-12-21T15:56:41.936+0000] {subprocess.py:93} INFO - #16 0x55e7527209ea <unknown>
[2023-12-21T15:56:41.938+0000] {subprocess.py:93} INFO - #17 0x55e752760689 <unknown>
[2023-12-21T15:56:41.939+0000] {subprocess.py:93} INFO - #18 0x55e75276086f <unknown>
[2023-12-21T15:56:41.940+0000] {subprocess.py:93} INFO - #19 0x55e75276f173 <unknown>
[2023-12-21T15:56:41.941+0000] {subprocess.py:93} INFO - #20 0x7f78d0adb3ec <unknown>
[2023-12-21T15:56:41.942+0000] {subprocess.py:93} INFO - 
[2023-12-21T15:56:41.944+0000] {subprocess.py:93} INFO - 
[2023-12-21T15:56:41.947+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2023-12-21T15:56:41.953+0000] {subprocess.py:93} INFO - 
[2023-12-21T15:56:41.956+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T15:56:41.957+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/webscrapinglinkedin/crawler.py", line 79, in <module>
[2023-12-21T15:56:41.958+0000] {subprocess.py:93} INFO -     if driver.find_element(By.XPATH, f'//*[@id="main-content"]/section[2]/button').text == 'Ver mais vagas':
[2023-12-21T15:56:41.960+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 741, in find_element
[2023-12-21T15:56:41.963+0000] {subprocess.py:93} INFO -     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
[2023-12-21T15:56:41.964+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
[2023-12-21T15:56:41.966+0000] {subprocess.py:93} INFO -     self.error_handler.check_response(response)
[2023-12-21T15:56:41.967+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2023-12-21T15:56:41.968+0000] {subprocess.py:93} INFO -     raise exception_class(message, screen, stacktrace)
[2023-12-21T15:56:41.969+0000] {subprocess.py:93} INFO - selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="main-content"]/section[2]/button"}
[2023-12-21T15:56:41.970+0000] {subprocess.py:93} INFO -   (Session info: headless chrome=117.0.5938.62); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
[2023-12-21T15:56:41.972+0000] {subprocess.py:93} INFO - Stacktrace:
[2023-12-21T15:56:41.973+0000] {subprocess.py:93} INFO - #0 0x55e75276fc07 <unknown>
[2023-12-21T15:56:41.975+0000] {subprocess.py:93} INFO - #1 0x55e75245403c <unknown>
[2023-12-21T15:56:41.976+0000] {subprocess.py:93} INFO - #2 0x55e752497222 <unknown>
[2023-12-21T15:56:41.977+0000] {subprocess.py:93} INFO - #3 0x55e752497345 <unknown>
[2023-12-21T15:56:41.979+0000] {subprocess.py:93} INFO - #4 0x55e7524cf668 <unknown>
[2023-12-21T15:56:41.986+0000] {subprocess.py:93} INFO - #5 0x55e7524b6c51 <unknown>
[2023-12-21T15:56:41.992+0000] {subprocess.py:93} INFO - #6 0x55e7524cd4e5 <unknown>
[2023-12-21T15:56:41.995+0000] {subprocess.py:93} INFO - #7 0x55e7524b69b7 <unknown>
[2023-12-21T15:56:41.997+0000] {subprocess.py:93} INFO - #8 0x55e75248bcad <unknown>
[2023-12-21T15:56:41.999+0000] {subprocess.py:93} INFO - #9 0x55e75248d266 <unknown>
[2023-12-21T15:56:42.000+0000] {subprocess.py:93} INFO - #10 0x55e752743c00 <unknown>
[2023-12-21T15:56:42.001+0000] {subprocess.py:93} INFO - #11 0x55e752746dad <unknown>
[2023-12-21T15:56:42.002+0000] {subprocess.py:93} INFO - #12 0x55e75274684a <unknown>
[2023-12-21T15:56:42.003+0000] {subprocess.py:93} INFO - #13 0x55e7527472c9 <unknown>
[2023-12-21T15:56:42.004+0000] {subprocess.py:93} INFO - #14 0x55e75274d7e3 <unknown>
[2023-12-21T15:56:42.006+0000] {subprocess.py:93} INFO - #15 0x55e752747666 <unknown>
[2023-12-21T15:56:42.007+0000] {subprocess.py:93} INFO - #16 0x55e7527209ea <unknown>
[2023-12-21T15:56:42.008+0000] {subprocess.py:93} INFO - #17 0x55e752760689 <unknown>
[2023-12-21T15:56:42.009+0000] {subprocess.py:93} INFO - #18 0x55e75276086f <unknown>
[2023-12-21T15:56:42.010+0000] {subprocess.py:93} INFO - #19 0x55e75276f173 <unknown>
[2023-12-21T15:56:42.011+0000] {subprocess.py:93} INFO - #20 0x7f78d0adb3ec <unknown>
[2023-12-21T15:56:42.012+0000] {subprocess.py:93} INFO - 
[2023-12-21T15:56:42.014+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-21T15:56:42.036+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-21T15:56:42.043+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scraping-jobs, task_id=test***, execution_date=20231221T155324, start_date=20231221T155635, end_date=20231221T155642
[2023-12-21T15:56:42.073+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 49 for task test*** (Bash command failed. The command returned a non-zero exit code 1.; 321)
[2023-12-21T15:56:42.104+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T15:56:42.143+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
