[2023-12-21T15:54:08.702+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509
[2023-12-21T15:54:08.703+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test***'
[2023-12-21T15:54:08.771+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509
[2023-12-21T15:54:08.773+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test***'
[2023-12-21T15:54:08.834+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:53:24.607881+00:00 [queued]>
[2023-12-21T15:54:08.850+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:53:24.607881+00:00 [queued]>
[2023-12-21T15:54:08.853+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-21T15:54:08.882+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): testairflow> on 2023-12-21 15:53:24.607881+00:00
[2023-12-21T15:54:08.894+0000] {standard_task_runner.py:57} INFO - Started process 282 to run task
[2023-12-21T15:54:08.902+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraping-jobs', 'test***', 'manual__2023-12-21T15:53:24.607881+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/webscrapinglinkedin/dag-webscrapinglinkedin.py', '--cfg-path', '/tmp/tmp77skoyws']
[2023-12-21T15:54:08.906+0000] {standard_task_runner.py:85} INFO - Job 47: Subtask test***
[2023-12-21T15:54:08.986+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509
[2023-12-21T15:54:08.988+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test***'
[2023-12-21T15:54:08.993+0000] {task_command.py:416} INFO - Running <TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:53:24.607881+00:00 [running]> on host cdaea2bd355d
[2023-12-21T15:54:09.119+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping-jobs' AIRFLOW_CTX_TASK_ID='test***' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T15:53:24.607881+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T15:53:24.607881+00:00'
[2023-12-21T15:54:09.122+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T15:54:09.124+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/webscrapinglinkedin/aux-pedreiro.py']
[2023-12-21T15:54:09.145+0000] {subprocess.py:86} INFO - Output:
[2023-12-21T15:54:34.250+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T15:54:34.252+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/webscrapinglinkedin/aux-pedreiro.py", line 14, in <module>
[2023-12-21T15:54:34.253+0000] {subprocess.py:93} INFO -     driver.get(url)
[2023-12-21T15:54:34.254+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
[2023-12-21T15:54:34.259+0000] {subprocess.py:93} INFO -     self.execute(Command.GET, {"url": url})
[2023-12-21T15:54:34.263+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
[2023-12-21T15:54:34.264+0000] {subprocess.py:93} INFO -     self.error_handler.check_response(response)
[2023-12-21T15:54:34.265+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2023-12-21T15:54:34.267+0000] {subprocess.py:93} INFO -     raise exception_class(message, screen, stacktrace)
[2023-12-21T15:54:34.268+0000] {subprocess.py:93} INFO - selenium.common.exceptions.InvalidSessionIdException: Message: Unable to execute request for an existing session: Unable to find session with ID: fce60b5a2395d713f902d632b7149388
[2023-12-21T15:54:34.269+0000] {subprocess.py:93} INFO - Build info: version: '4.10.0', revision: 'c14d967899'
[2023-12-21T15:54:34.271+0000] {subprocess.py:93} INFO - System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.20'
[2023-12-21T15:54:34.289+0000] {subprocess.py:93} INFO - Driver info: driver.version: unknown
[2023-12-21T15:54:34.293+0000] {subprocess.py:93} INFO - 
[2023-12-21T15:54:34.314+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-21T15:54:34.353+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-21T15:54:34.365+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scraping-jobs, task_id=test***, execution_date=20231221T155324, start_date=20231221T155408, end_date=20231221T155434
[2023-12-21T15:54:34.395+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 47 for task test*** (Bash command failed. The command returned a non-zero exit code 1.; 282)
[2023-12-21T15:54:34.449+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T15:54:34.476+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
