[2023-12-21T14:42:30.061+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T14:39:23.642585+00:00/task_id=test*** permission to 509
[2023-12-21T14:42:30.068+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T14:39:23.642585+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T14:39:23.642585+00:00/task_id=test***'
[2023-12-21T14:42:30.125+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T14:39:23.642585+00:00/task_id=test*** permission to 509
[2023-12-21T14:42:30.127+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T14:39:23.642585+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T14:39:23.642585+00:00/task_id=test***'
[2023-12-21T14:42:30.211+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T14:39:23.642585+00:00 [queued]>
[2023-12-21T14:42:30.240+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T14:39:23.642585+00:00 [queued]>
[2023-12-21T14:42:30.241+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-21T14:42:30.276+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): testairflow> on 2023-12-21 14:39:23.642585+00:00
[2023-12-21T14:42:30.290+0000] {standard_task_runner.py:57} INFO - Started process 624 to run task
[2023-12-21T14:42:30.296+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraping-jobs', 'test***', 'manual__2023-12-21T14:39:23.642585+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dag-webscrappinglinkedin.py', '--cfg-path', '/tmp/tmp6zmqzxk2']
[2023-12-21T14:42:30.301+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask test***
[2023-12-21T14:42:30.395+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T14:39:23.642585+00:00/task_id=test*** permission to 509
[2023-12-21T14:42:30.400+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T14:39:23.642585+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T14:39:23.642585+00:00/task_id=test***'
[2023-12-21T14:42:30.407+0000] {task_command.py:416} INFO - Running <TaskInstance: scraping-jobs.testairflow manual__2023-12-21T14:39:23.642585+00:00 [running]> on host ae1e32dc581d
[2023-12-21T14:42:30.586+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping-jobs' AIRFLOW_CTX_TASK_ID='test***' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T14:39:23.642585+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T14:39:23.642585+00:00'
[2023-12-21T14:42:30.590+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T14:42:30.593+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/apps/crawler.py']
[2023-12-21T14:42:30.621+0000] {subprocess.py:86} INFO - Output:
[2023-12-21T14:42:36.268+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T14:42:36.270+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/apps/crawler.py", line 47, in <module>
[2023-12-21T14:42:36.271+0000] {subprocess.py:93} INFO -     driver.get(url)
[2023-12-21T14:42:36.272+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
[2023-12-21T14:42:36.273+0000] {subprocess.py:93} INFO -     self.execute(Command.GET, {"url": url})
[2023-12-21T14:42:36.281+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
[2023-12-21T14:42:36.282+0000] {subprocess.py:93} INFO -     self.error_handler.check_response(response)
[2023-12-21T14:42:36.285+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
[2023-12-21T14:42:36.286+0000] {subprocess.py:93} INFO -     raise exception_class(message, screen, stacktrace)
[2023-12-21T14:42:36.287+0000] {subprocess.py:93} INFO - selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
[2023-12-21T14:42:36.288+0000] {subprocess.py:93} INFO - from unknown error: cannot determine loading status
[2023-12-21T14:42:36.289+0000] {subprocess.py:93} INFO - from tab crashed
[2023-12-21T14:42:36.290+0000] {subprocess.py:93} INFO -   (Session info: headless chrome=117.0.5938.62)
[2023-12-21T14:42:36.297+0000] {subprocess.py:93} INFO - Stacktrace:
[2023-12-21T14:42:36.299+0000] {subprocess.py:93} INFO - #0 0x56268a328c07 <unknown>
[2023-12-21T14:42:36.300+0000] {subprocess.py:93} INFO - #1 0x56268a00cd4a <unknown>
[2023-12-21T14:42:36.302+0000] {subprocess.py:93} INFO - #2 0x562689ff8733 <unknown>
[2023-12-21T14:42:36.303+0000] {subprocess.py:93} INFO - #3 0x562689ff7678 <unknown>
[2023-12-21T14:42:36.305+0000] {subprocess.py:93} INFO - #4 0x562689ff7c7d <unknown>
[2023-12-21T14:42:36.312+0000] {subprocess.py:93} INFO - #5 0x56268a004dd8 <unknown>
[2023-12-21T14:42:36.314+0000] {subprocess.py:93} INFO - #6 0x56268a017703 <unknown>
[2023-12-21T14:42:36.315+0000] {subprocess.py:93} INFO - #7 0x56268a01b8bf <unknown>
[2023-12-21T14:42:36.317+0000] {subprocess.py:93} INFO - #8 0x562689ff814e <unknown>
[2023-12-21T14:42:36.318+0000] {subprocess.py:93} INFO - #9 0x56268a0173e6 <unknown>
[2023-12-21T14:42:36.319+0000] {subprocess.py:93} INFO - #10 0x56268a086733 <unknown>
[2023-12-21T14:42:36.321+0000] {subprocess.py:93} INFO - #11 0x56268a06f9b7 <unknown>
[2023-12-21T14:42:36.322+0000] {subprocess.py:93} INFO - #12 0x56268a044cad <unknown>
[2023-12-21T14:42:36.324+0000] {subprocess.py:93} INFO - #13 0x56268a046266 <unknown>
[2023-12-21T14:42:36.327+0000] {subprocess.py:93} INFO - #14 0x56268a2fcc00 <unknown>
[2023-12-21T14:42:36.328+0000] {subprocess.py:93} INFO - #15 0x56268a2ffdad <unknown>
[2023-12-21T14:42:36.329+0000] {subprocess.py:93} INFO - #16 0x56268a2ff84a <unknown>
[2023-12-21T14:42:36.331+0000] {subprocess.py:93} INFO - #17 0x56268a3002c9 <unknown>
[2023-12-21T14:42:36.332+0000] {subprocess.py:93} INFO - #18 0x56268a3067e3 <unknown>
[2023-12-21T14:42:36.333+0000] {subprocess.py:93} INFO - #19 0x56268a300666 <unknown>
[2023-12-21T14:42:36.334+0000] {subprocess.py:93} INFO - #20 0x56268a2d99ea <unknown>
[2023-12-21T14:42:36.335+0000] {subprocess.py:93} INFO - #21 0x56268a319689 <unknown>
[2023-12-21T14:42:36.337+0000] {subprocess.py:93} INFO - #22 0x56268a31986f <unknown>
[2023-12-21T14:42:36.338+0000] {subprocess.py:93} INFO - #23 0x56268a328173 <unknown>
[2023-12-21T14:42:36.339+0000] {subprocess.py:93} INFO - #24 0x7fa9c0d7e3ec <unknown>
[2023-12-21T14:42:36.348+0000] {subprocess.py:93} INFO - 
[2023-12-21T14:42:36.373+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-21T14:42:36.397+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-21T14:42:36.406+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scraping-jobs, task_id=test***, execution_date=20231221T143923, start_date=20231221T144230, end_date=20231221T144236
[2023-12-21T14:42:36.450+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 22 for task test*** (Bash command failed. The command returned a non-zero exit code 1.; 624)
[2023-12-21T14:42:36.475+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T14:42:36.504+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
